name: ipynbcompress-ci-build
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:

  run-tests:

    strategy:
      matrix:
        python-version: ["3.8", "3.11"]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install package via pip
      run: |
        pip install pytest
        pip install -r requirements.txt

    - name: Run tests
      run: pytest